name: Run Kaggle Notebook Daily

on:
  schedule:
    - cron: "0 6 * * *"  # Runs daily at 6 AM UTC

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Kaggle API
        run: pip install kaggle

      - name: Set up Kaggle API credentials
        run: |
          mkdir -p ~/.kaggle
          echo "{\"username\":\"${{ secrets.KAGGLE_USERNAME }}\",\"key\":\"${{ secrets.KAGGLE_KEY }}\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Push Notebook to Kaggle
        run: kaggle kernels push -p .
